spring.application.name=barber
# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/barber
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


# SEGURIDAD
#Par�metros de seguridad
security.jwt.token.secret-key=${BARBER_SECRET_KEY}
#Tiempo de expiracion del JWT en minutos
security.jwt.token.expire-length=480

#Parametros de conexion al Sistema 1
sistema1.url-base=http://172.16.75.31:8080
sistema1.connect-timeout=1000
sistema1.read-timeout=2000

# Parametros de conexion a Stereum Pay
stereum.url-base=https://api.stereum.tech
stereum.api-key=${STEREUM_API_KEY}
stereum.api-secret=${STEREUM_SECRET_KEY}
stereum.connect-timeout=10000
stereum.read-timeout=40000


async.core-pool-size = 5
async.max-pool-size = 10
async.queue-capacity = 20