spring.application.name=barber
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/barber_db
spring.datasource.username=postgres
spring.datasource.password=Alassio42
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true