spring.application.name=barber
# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/barber
spring.datasource.username=barber_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# SEGURIDAD
#Parámetros de seguridad
security.jwt.token.secret-key=pQKOkAZ8j59Kb6QJC+LHL7viCKLrfhBZ7PjGeIznKbY=
#Tiempo de expiración del JWT en minutos
security.jwt.token.expire-length=480

#spring.application.name=barber
## Conexión a PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/barber
#spring.datasource.username=barber_user
#spring.datasource.password=12345
#spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA / Hibernate
##spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
##crear y actualizar en bd
## en produccion nunca subir con create-drop
## none: no hace nada
## defino una tabla en codigo y se crea en db
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
