spring.application.name=springsito
spring.datasource.url=jdbc:postgresql://localhost:5434/pelaje
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Juan3:16
spring.jpa.hibernate.ddl-auto=update 
server.port=8002
